export interface ReformaArticle {
  id: string;
  title: string;
  summary: string;
  category: 'fundamentos' | 'operacoes' | 'setores' | 'regimes' | 'contratos' | 'planejamento';
  categoryLabel: string;
  tags: string[];
  icon: string;
  difficulty: 'basico' | 'intermediario' | 'avancado';
  readTime: number;
  lawBasis: string[];
  featured: boolean;
  sections: {
    oquedizalei: string;
    oquemudata: string;
    oquefarzer: string;
    baseLegal: string;
  };
  relatedArticles: string[];
  planActionIds: string[];
}

export const CATEGORY_CONFIG: Record<string, { label: string; color: string }> = {
  fundamentos:  { label: 'Fundamentos',             color: 'bg-blue-500/20 text-blue-300 border border-blue-500/30' },
  operacoes:    { label: 'Operações e Tecnologia',   color: 'bg-orange-500/20 text-orange-300 border border-orange-500/30' },
  setores:      { label: 'Setores da Economia',      color: 'bg-green-500/20 text-green-300 border border-green-500/30' },
  regimes:      { label: 'Regimes Tributários',      color: 'bg-purple-500/20 text-purple-300 border border-purple-500/30' },
  contratos:    { label: 'Contratos e Preços',       color: 'bg-yellow-500/20 text-yellow-300 border border-yellow-500/30' },
  planejamento: { label: 'Planejamento e Adequação', color: 'bg-red-500/20 text-red-300 border border-red-500/30' },
};

export const DIFFICULTY_CONFIG: Record<string, { label: string; color: string }> = {
  basico:        { label: 'Básico',         color: 'bg-green-500/20 text-green-300' },
  intermediario: { label: 'Intermediário',  color: 'bg-yellow-500/20 text-yellow-300' },
  avancado:      { label: 'Avançado',       color: 'bg-red-500/20 text-red-300' },
};

export const reformaArticles: ReformaArticle[] = [
  {
    id: 'ibs',
    title: 'IBS — Imposto sobre Bens e Serviços',
    summary: 'O IBS unifica a tributação de estados e municípios, substituindo ICMS e ISS por um único imposto não cumulativo com legislação nacional.',
    category: 'fundamentos',
    categoryLabel: 'Fundamentos',
    tags: ['ibs', 'icms', 'iss', 'estados', 'municipios', 'nao-cumulativo'],
    icon: 'BookOpen',
    difficulty: 'basico',
    readTime: 4,
    lawBasis: ['EC 132/2023', 'LC 214/2025'],
    featured: true,
    sections: {
      oquedizalei: 'A EC 132/2023 criou o IBS no Art. 156-A da Constituição Federal, regulamentado pela LC 214/2025. Ele substitui o ICMS (estadual) e o ISS (municipal), com competência compartilhada entre estados e municípios. É não cumulativo: cada etapa da cadeia desconta o imposto pago na etapa anterior.',
      oquemudata: 'Hoje uma empresa lida com 27 legislações estaduais de ICMS e mais de 5.000 leis municipais de ISS. Com o IBS, há uma única legislação nacional, alíquota uniforme e gestão pelo Comitê Gestor do IBS. Quem vende para vários estados não precisará mais parametrizar ICMS diferente para cada UF.',
      oquefarzer: 'Atualize o ERP para os novos campos de IBS nas notas fiscais. Revise cadastros de produtos. Acompanhe a definição da alíquota de referência pelo Senado. Mapeie os benefícios fiscais de ICMS estaduais que sua empresa utiliza — serão extintos até 2033.',
      baseLegal: 'Art. 156-A, CF/88 inserido pela EC 132/2023; LC 214/2025, Arts. 1º ao 350.',
    },
    relatedArticles: ['cbs', 'iva-dual', 'calendario-transicao', 'operacoes-entre-estados'],
    planActionIds: ['erp_contact', 'catalog_std', 'multistate_erp'],
  },
  {
    id: 'cbs',
    title: 'CBS — Contribuição sobre Bens e Serviços',
    summary: 'A CBS substitui PIS e COFINS com alíquota uniforme, regime não cumulativo e crédito amplo sobre praticamente todas as despesas da empresa.',
    category: 'fundamentos',
    categoryLabel: 'Fundamentos',
    tags: ['cbs', 'pis', 'cofins', 'federal', 'credito', 'nao-cumulativo'],
    icon: 'FileText',
    difficulty: 'basico',
    readTime: 4,
    lawBasis: ['EC 132/2023', 'LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'A EC 132/2023 autorizou a criação da CBS (Art. 195, V, CF/88), regulamentada pela LC 214/2025. Ela substitui o PIS e a COFINS, de competência federal. É não cumulativa e permite crédito sobre praticamente todas as aquisições usadas nas atividades da empresa.',
      oquemudata: 'PIS e COFINS têm regimes cumulativos e não cumulativos, alíquotas variadas e créditos restritos. A CBS simplifica: uma alíquota, uma legislação, crédito amplo. Para o Lucro Real, a transição tende a ser menos traumática. Para o Lucro Presumido, onde PIS/COFINS são calculados sem crédito, a mudança exige simulação cuidadosa.',
      oquefarzer: 'Mapeie o volume atual de PIS/COFINS pago e projete como será com a CBS. Revise contratos e preços considerando a nova lógica de crédito. Garanta que todas as notas fiscais de entrada estejam registradas corretamente para aproveitamento de crédito.',
      baseLegal: 'Art. 195, V, CF/88 inserido pela EC 132/2023; LC 214/2025.',
    },
    relatedArticles: ['ibs', 'credito-amplo', 'lucro-presumido', 'lucro-real'],
    planActionIds: ['erp_contact', 'fiscal_routine', 'regime_transition'],
  },
  {
    id: 'imposto-seletivo',
    title: 'Imposto Seletivo (IS) — tributo sobre produtos prejudiciais',
    summary: 'O IS incide sobre bens prejudiciais à saúde ou ao meio ambiente e NÃO gera crédito na cadeia — é um custo tributário definitivo.',
    category: 'fundamentos',
    categoryLabel: 'Fundamentos',
    tags: ['imposto-seletivo', 'is', 'tabaco', 'bebidas', 'veiculos', 'ipi'],
    icon: 'AlertTriangle',
    difficulty: 'intermediario',
    readTime: 3,
    lawBasis: ['EC 132/2023', 'LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'Criado pelo Art. 153, VIII da CF/88 (EC 132/2023), o IS é federal e incide sobre produção, extração, comercialização ou importação de bens prejudiciais à saúde ou ao meio ambiente. Diferente do IBS e CBS, o IS NÃO gera crédito — é custo definitivo na cadeia.',
      oquemudata: 'O IS substitui a função extrafiscal do IPI para produtos específicos. Estão sujeitos: fumo e derivados, bebidas alcoólicas, bebidas açucaradas, veículos automotores, aquáticos e aéreos, e bens prejudiciais ao meio ambiente. Sua empresa produz, importa ou comercializa esses produtos? O IS será um custo puro sem compensação.',
      oquefarzer: 'Verifique se algum produto da sua operação está na lista do IS. Se estiver, calcule o impacto definitivo no custo e revise a precificação — não há crédito para compensar o IS.',
      baseLegal: 'Art. 153, VIII, CF/88 (EC 132/2023); LC 214/2025, capítulo do Imposto Seletivo.',
    },
    relatedArticles: ['ibs', 'cbs', 'industria'],
    planActionIds: ['top30_items', 'pricing_formula'],
  },
  {
    id: 'iva-dual',
    title: 'IVA Dual — por que o Brasil criou dois tributos',
    summary: 'O Brasil adotou IVA Dual (IBS + CBS) para preservar a autonomia dos entes federativos. Na prática: duas alíquotas na nota, uma só burocracia.',
    category: 'fundamentos',
    categoryLabel: 'Fundamentos',
    tags: ['iva', 'iva-dual', 'federalismo', 'comite-gestor', 'simplificacao'],
    icon: 'Scale',
    difficulty: 'basico',
    readTime: 3,
    lawBasis: ['EC 132/2023', 'LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'A EC 132/2023 optou por um IVA Dual: o IBS (competência de estados e municípios) e a CBS (competência federal) funcionam com regras unificadas mas gerenciados separadamente. O Comitê Gestor do IBS coordena os 27 estados e mais de 5.500 municípios.',
      oquemudata: 'Em países como Portugal e Alemanha há um único IVA nacional. No Brasil, a estrutura federativa impediu isso. O resultado: a nota fiscal mostrará dois valores (IBS e CBS), mas a lógica de cálculo, crédito e obrigações acessórias é unificada. Você lida com dois tributos, mas com uma única burocracia nacional.',
      oquefarzer: 'Entenda que IBS e CBS se comportam de forma similar, mas com destinos de arrecadação diferentes. Seu ERP precisará registrar ambos separadamente. Acompanhe as resoluções do Comitê Gestor do IBS para detalhes das obrigações estaduais e municipais.',
      baseLegal: 'EC 132/2023; LC 214/2025, Arts. sobre o Comitê Gestor do IBS.',
    },
    relatedArticles: ['ibs', 'cbs', 'calendario-transicao'],
    planActionIds: ['governance_setup'],
  },
  {
    id: 'calendario-transicao',
    title: 'Calendário da Transição 2026–2033',
    summary: 'A reforma será implementada em 8 anos. Em 2026 adapte sistemas. Em 2027 começa o recolhimento. Em 2033 os tributos antigos são extintos.',
    category: 'fundamentos',
    categoryLabel: 'Fundamentos',
    tags: ['transicao', 'calendario', '2026', '2027', '2033', 'cronograma', 'icms', 'iss'],
    icon: 'Calendar',
    difficulty: 'basico',
    readTime: 5,
    lawBasis: ['EC 132/2023', 'LC 214/2025'],
    featured: true,
    sections: {
      oquedizalei: 'A EC 132/2023 e a LC 214/2025 estabelecem transição de 2026 a 2033. IBS, CBS e tributos antigos (ICMS, ISS, PIS, COFINS) convivem simultaneamente, com redução gradual dos antigos e aumento gradual dos novos.',
      oquemudata: '2026: Ano informativo — IBS e CBS são calculados e informados nas NFs, mas sem recolhimento. 2027–2028: IBS 0,1% + CBS 0,9% (alíquotas reduzidas para teste real). 2029–2032: Redução progressiva de ICMS, ISS, PIS e COFINS; aumento de IBS e CBS. 2033: Extinção total dos tributos antigos.',
      oquefarzer: 'Monte um cronograma interno com as datas críticas. Foque em 2026 para adaptação dos sistemas. Prepare-se para os primeiros recolhimentos em 2027. Identifique e planeje o fim dos benefícios fiscais de ICMS que sua empresa utiliza.',
      baseLegal: 'EC 132/2023, disposições transitórias; LC 214/2025, cronograma de implementação.',
    },
    relatedArticles: ['ibs', 'cbs', 'nota-fiscal', 'ano-informativo-2026'],
    planActionIds: ['mgmt_briefing', 'team_training', 'final_validation'],
  },
  {
    id: 'split-payment',
    title: 'Split Payment — o imposto vai direto para o fisco',
    summary: 'Com o Split Payment, IBS e CBS são retidos automaticamente pela instituição financeira no pagamento. O valor do imposto nunca entra na conta da empresa.',
    category: 'operacoes',
    categoryLabel: 'Operações e Tecnologia',
    tags: ['split-payment', 'fluxo-de-caixa', 'banco', 'cartao', 'retencao', 'capital-de-giro'],
    icon: 'Wallet',
    difficulty: 'intermediario',
    readTime: 5,
    lawBasis: ['LC 214/2025'],
    featured: true,
    sections: {
      oquedizalei: 'A LC 214/2025 instituiu o Split Payment: no momento em que o comprador paga, a instituição financeira (banco, adquirente de cartão) separa automaticamente o valor do tributo e repassa diretamente ao fisco, sem passar pela conta do vendedor.',
      oquemudata: 'Hoje a empresa recebe o valor cheio, guarda o imposto e recolhe no vencimento. Com o Split Payment, o valor do imposto nunca chega à conta — é retido na fonte. Empresas que usavam o "float" do imposto para capital de giro sentirão o impacto imediatamente. Para pagamentos em espécie, o Split Payment não se aplica diretamente.',
      oquefarzer: 'Simule o impacto no fluxo de caixa: calcule a diferença entre o capital de giro atual e o disponível após o Split Payment. Se necessário, renegocie prazos com fornecedores ou busque linhas de crédito preventivamente. Não espere 2027 para essa simulação.',
      baseLegal: 'LC 214/2025, Arts. sobre Split Payment e recolhimento automático.',
    },
    relatedArticles: ['ano-informativo-2026', 'calendario-transicao', 'varejo-comercio'],
    planActionIds: ['split_simulation'],
  },
  {
    id: 'credito-amplo',
    title: 'Crédito Amplo — aproveitando ao máximo os créditos',
    summary: 'A reforma amplia o direito ao crédito: praticamente todos os insumos, serviços e despesas geram crédito de IBS e CBS, rompendo com as restrições atuais do PIS/COFINS.',
    category: 'operacoes',
    categoryLabel: 'Operações e Tecnologia',
    tags: ['credito', 'nao-cumulativo', 'insumos', 'despesas', 'pis', 'cofins', 'beneficio'],
    icon: 'TrendingUp',
    difficulty: 'intermediario',
    readTime: 4,
    lawBasis: ['LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'A LC 214/2025 estabelece o crédito amplo: geram direito a crédito de IBS e CBS todas as aquisições de bens e serviços usados nas atividades da empresa, incluindo insumos, ativos, despesas gerais e serviços. É uma ruptura com o PIS/COFINS atual, que tem lista restrita de créditos.',
      oquemudata: 'Hoje uma empresa no Lucro Real tem crédito de PIS/COFINS apenas em situações específicas. Com a CBS, despesas como aluguel, consultorias, energia elétrica e TI passam a gerar crédito integralmente. Para indústrias com cadeias longas, o benefício é expressivo. Para empresas de pouco insumo, a alíquota maior sobre a receita pode superar o ganho.',
      oquefarzer: 'Mapeie todas as despesas que hoje não geram crédito de PIS/COFINS e calcule quanto crédito será gerado com a CBS. Isso é fundamental para projeção de caixa, precificação e escolha do regime tributário mais vantajoso.',
      baseLegal: 'LC 214/2025, Arts. sobre não-cumulatividade e crédito amplo.',
    },
    relatedArticles: ['cbs', 'lucro-real', 'simples-nacional', 'industria'],
    planActionIds: ['supplier_abc', 'supplier_nf_quality', 'fiscal_routine'],
  },
  {
    id: 'nota-fiscal',
    title: 'Nota Fiscal na Reforma — novos campos obrigatórios',
    summary: 'A partir de 2026, NF-e e NFS-e precisam registrar IBS, CBS e IS em campos específicos. Sistemas desatualizados comprometem os créditos dos seus clientes.',
    category: 'operacoes',
    categoryLabel: 'Operações e Tecnologia',
    tags: ['nota-fiscal', 'nfe', 'erp', 'documentos-fiscais', 'obrigacoes', 'layout'],
    icon: 'FileCheck',
    difficulty: 'basico',
    readTime: 3,
    lawBasis: ['LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'A LC 214/2025, junto com atos normativos da Receita Federal e do Comitê Gestor do IBS, determina que documentos fiscais eletrônicos (NF-e, NFS-e, CT-e) incluam campos específicos para IBS, CBS e IS, com alíquotas, bases de cálculo e valores separados.',
      oquemudata: 'Em 2026, as notas já devem conter esses campos mesmo sem recolhimento. Sistemas desatualizados geram inconsistências nos créditos dos seus clientes B2B — um problema direto no relacionamento comercial. Emissores gratuitos da SEFAZ e ERPs precisarão de atualização.',
      oquefarzer: 'Verifique com o fornecedor do seu sistema quando a atualização para os novos layouts estará disponível. Faça testes de emissão antes de 2027. Não deixe para a última hora — atualizações de layout fiscal costumam ter problemas no início.',
      baseLegal: 'LC 214/2025; Notas Técnicas da SEFAZ Nacional e Comitê Gestor do IBS.',
    },
    relatedArticles: ['ano-informativo-2026', 'split-payment', 'infracoes-penalidades'],
    planActionIds: ['erp_contact', 'erp_adoption', 'catalog_std', 'nfe_test'],
  },
  {
    id: 'ano-informativo-2026',
    title: '2026 é Ano Informativo — o que isso significa',
    summary: 'Empresas calculam e informam IBS/CBS nas notas em 2026, mas não recolhem. É o prazo final para adaptar sistemas antes que o pagamento comece em 2027.',
    category: 'operacoes',
    categoryLabel: 'Operações e Tecnologia',
    tags: ['2026', 'informativo', 'adaptacao', 'sistemas', 'teste', 'prazo'],
    icon: 'Info',
    difficulty: 'basico',
    readTime: 3,
    lawBasis: ['LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'A LC 214/2025 determinou que 2026 seja período de teste informativo. Os contribuintes devem calcular IBS e CBS e registrar nos documentos fiscais, mas ficam dispensados do recolhimento efetivo. O objetivo é calibrar sistemas e identificar inconsistências antes do recolhimento começar em 2027.',
      oquemudata: 'Isso não significa que 2026 é um ano tranquilo. É o momento certo para ajustar sistemas, treinar equipes e revisar cadastros — sem o custo imediato de recolhimento. Empresas que ignorarem 2026 chegarão em 2027 sem sistemas adaptados e com risco de autuação por falha nas obrigações acessórias.',
      oquefarzer: 'Trate 2026 como prazo final para adaptação técnica — não como uma pausa. Verifique se o ERP já gera os campos de IBS/CBS corretamente. Faça conciliações mensais e identifique divergências antes que virem penalidades.',
      baseLegal: 'LC 214/2025, disposições sobre o período de teste 2026.',
    },
    relatedArticles: ['nota-fiscal', 'calendario-transicao', 'infracoes-penalidades'],
    planActionIds: ['erp_contact', 'erp_adoption', 'governance_setup'],
  },
  {
    id: 'aliquota-referencia',
    title: 'Alíquota de Referência — qual será o percentual',
    summary: 'A alíquota combinada de IBS+CBS ainda será definida pelo Senado. Estimativas apontam entre 26% e 28%, mas o impacto real depende dos créditos de cada empresa.',
    category: 'operacoes',
    categoryLabel: 'Operações e Tecnologia',
    tags: ['aliquota', 'referencia', 'senado', 'percentual', 'carga-tributaria', 'simulacao'],
    icon: 'Percent',
    difficulty: 'intermediario',
    readTime: 4,
    lawBasis: ['EC 132/2023', 'LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'A EC 132/2023 determina que a alíquota de referência do IBS seja fixada pelo Senado por resolução. A da CBS será por lei federal. O critério: a soma de IBS + CBS deve manter a mesma arrecadação atual de ICMS + ISS + PIS + COFINS — sem intenção de aumento de carga global.',
      oquemudata: 'Estimativas técnicas apontam alíquota combinada entre 26% e 28% sobre o valor das operações. Parece alto, mas com o crédito amplo o impacto líquido para a maioria das empresas é muito diferente da alíquota nominal. Para setores diferenciados (saúde, educação, agronegócio), alíquotas serão menores.',
      oquefarzer: 'Acompanhe a definição da alíquota pelo Senado. Faça simulações com diferentes cenários para seu setor, considerando os créditos que sua empresa terá direito. A alíquota nominal alta não é o número mais importante — o que importa é a carga efetiva após os créditos.',
      baseLegal: 'EC 132/2023, Art. 156-B (IBS); Art. 195, V, CF/88 (CBS); LC 214/2025.',
    },
    relatedArticles: ['ibs', 'cbs', 'credito-amplo', 'calendario-transicao'],
    planActionIds: ['pricing_formula', 'top30_items'],
  },
  {
    id: 'regime-monofasico',
    title: 'Regime Monofásico — tributação concentrada na origem',
    summary: 'No monofásico, IBS e CBS são recolhidos em uma única etapa da cadeia, com crédito presumido para as demais. Aplicável a combustíveis, medicamentos e similares.',
    category: 'operacoes',
    categoryLabel: 'Operações e Tecnologia',
    tags: ['monofasico', 'combustiveis', 'medicamentos', 'credito-presumido', 'cadeia'],
    icon: 'Layers',
    difficulty: 'avancado',
    readTime: 4,
    lawBasis: ['LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'A LC 214/2025 mantém o regime monofásico para setores específicos: a tributação se concentra no produtor ou importador, e as etapas seguintes recebem créditos presumidos. Já existe hoje para combustíveis, medicamentos e cigarros.',
      oquemudata: 'Empresas distribuidoras ou revendedoras de produtos monofásicos continuarão recebendo créditos presumidos — mas a metodologia muda com o IBS/CBS. O crédito presumido do novo regime pode ter valor diferente do atual. Fundamental verificar os produtos da sua operação.',
      oquefarzer: 'Identifique se algum produto da sua operação está sob regime monofásico de ICMS, PIS ou COFINS. Consulte o regulamento específico do IBS/CBS para esses produtos. A transição tem regras próprias que exigem acompanhamento.',
      baseLegal: 'LC 214/2025, capítulo sobre regimes específicos e regime monofásico.',
    },
    relatedArticles: ['credito-amplo', 'industria', 'agronegocio'],
    planActionIds: ['top30_items', 'catalog_std'],
  },
  {
    id: 'varejo-comercio',
    title: 'Varejo e Comércio — o que muda nas vendas ao consumidor',
    summary: 'O varejo sente o Split Payment no caixa, ganha crédito amplo nas compras e passa para tributação por destino nas vendas interestaduais.',
    category: 'setores',
    categoryLabel: 'Setores da Economia',
    tags: ['varejo', 'comercio', 'b2c', 'consumidor', 'pdv', 'split-payment', 'loja'],
    icon: 'ShoppingCart',
    difficulty: 'intermediario',
    readTime: 4,
    lawBasis: ['EC 132/2023', 'LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'Para o varejo B2C, IBS e CBS incidem no destino (onde está o consumidor), substituindo o ICMS de origem e o ISS municipal. O Split Payment muda o fluxo financeiro, e o crédito amplo beneficia as compras de mercadorias de fornecedores com nota regular.',
      oquemudata: 'Uma loja que hoje paga ICMS sobre venda e PIS/COFINS sobre receita passará a pagar IBS+CBS com crédito das compras. Quem compra de fornecedores com NF regular tende a ter créditos maiores do que hoje. O maior impacto: com o Split Payment, o imposto não passa mais pela conta da empresa.',
      oquefarzer: 'Simule a carga tributária com IBS+CBS comparada ao atual. Revise a precificação considerando a nova estrutura de créditos. Prepare o PDV para os novos campos fiscais. Avalie o impacto do Split Payment no capital de giro com antecedência.',
      baseLegal: 'EC 132/2023; LC 214/2025.',
    },
    relatedArticles: ['split-payment', 'credito-amplo', 'reajuste-precos', 'cashback'],
    planActionIds: ['b2c_pricing_comms', 'split_simulation', 'marketplace_reform'],
  },
  {
    id: 'setor-imobiliario',
    title: 'Setor Imobiliário e Construção Civil',
    summary: 'O setor imobiliário tem regime diferenciado com alíquota e crédito próprios para incorporação, venda e locação. Cada tipo de operação tem enquadramento específico.',
    category: 'setores',
    categoryLabel: 'Setores da Economia',
    tags: ['imobiliario', 'construcao', 'incorporacao', 'locacao', 'regime-diferenciado', 'imoveis'],
    icon: 'Building2',
    difficulty: 'avancado',
    readTime: 5,
    lawBasis: ['LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'A LC 214/2025 estabelece regime diferenciado para o setor imobiliário: venda de imóveis residenciais novos, locação e serviços de incorporação têm regras de alíquota e crédito distintas das operações gerais.',
      oquemudata: 'Hoje o setor sofre com cumulatividade e falta de crédito nas etapas da cadeia (terreno, construção, venda). Com a reforma, a cadeia fica mais transparente, com possibilidade de crédito em insumos de construção. Porém, a incidência de IBS/CBS sobre operações que hoje não pagam ICMS ou ISS pode aumentar carga em casos específicos.',
      oquefarzer: 'Mapeie cada tipo de operação (incorporação, venda, locação, reforma) e consulte assessoria tributária para entender o enquadramento de cada uma no regime diferenciado. A LC 214/2025 tem regras próprias para esse setor que exigem análise individualizada.',
      baseLegal: 'LC 214/2025, capítulo sobre regime diferenciado para o setor imobiliário.',
    },
    relatedArticles: ['credito-amplo', 'contratos-longo-prazo', 'operacoes-entre-estados'],
    planActionIds: ['top30_items', 'contracts_review'],
  },
  {
    id: 'agronegocio',
    title: 'Agronegócio — cesta básica, alíquota zero e créditos',
    summary: 'Produtos da cesta básica têm alíquota zero. Os demais produtos agropecuários têm alíquota reduzida. Insumos agrícolas geram crédito pleno na cadeia.',
    category: 'setores',
    categoryLabel: 'Setores da Economia',
    tags: ['agronegocio', 'cesta-basica', 'aliquota-zero', 'insumos', 'rural', 'alimentos'],
    icon: 'Wheat',
    difficulty: 'intermediario',
    readTime: 4,
    lawBasis: ['EC 132/2023', 'LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'A EC 132/2023 e a LC 214/2025 estabelecem alíquota zero de IBS e CBS para produtos da cesta básica nacional. Produtos agropecuários fora da cesta têm alíquota reduzida. A cadeia mantém direito a crédito dos insumos (sementes, adubos, defensivos, máquinas).',
      oquemudata: 'Uma empresa que processa alimentos da cesta básica pode ter alíquota zero na saída mas crédito dos insumos — gerando saldo credor para compensação ou ressarcimento. Para produtos agropecuários fora da cesta, a alíquota reduzida representa mudança em relação ao ICMS estadual, que varia muito por UF.',
      oquefarzer: 'Identifique quais produtos se enquadram na cesta básica, quais têm alíquota reduzida e quais seguem a alíquota padrão. Calcule o saldo de créditos e o impacto líquido comparado ao sistema atual. Mapeie os benefícios de ICMS rurais estaduais que serão extintos.',
      baseLegal: 'EC 132/2023; LC 214/2025, disposições sobre cesta básica e agronegócio.',
    },
    relatedArticles: ['regime-monofasico', 'credito-amplo', 'operacoes-entre-estados'],
    planActionIds: ['top30_items', 'export_rules'],
  },
  {
    id: 'saude',
    title: 'Saúde — alíquota reduzida e enquadramento correto',
    summary: 'Serviços de saúde têm alíquota reduzida prevista, mas não de forma automática. Cada atividade precisa ser verificada individualmente no regime diferenciado.',
    category: 'setores',
    categoryLabel: 'Setores da Economia',
    tags: ['saude', 'clinica', 'hospital', 'medicamentos', 'aliquota-reduzida', 'regime-diferenciado'],
    icon: 'Stethoscope',
    difficulty: 'intermediario',
    readTime: 4,
    lawBasis: ['LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'A LC 214/2025 prevê alíquota reduzida para serviços de saúde humana, medicamentos e dispositivos médicos listados. O enquadramento depende da atividade: serviços médicos, hospitalares e clínicas têm tratamento distinto de atividades administrativas e de suporte.',
      oquemudata: 'Uma clínica que hoje paga ISS de 2% a 5% e PIS/COFINS passará para IBS+CBS com alíquota reduzida. O impacto depende do nível de crédito atual e da alíquota efetiva no novo sistema — pode haver aumento ou redução de carga. Planos de saúde seguem regras de serviços financeiros.',
      oquefarzer: 'Mapeie cada atividade da empresa e verifique o enquadramento no regime de saúde da LC 214/2025. Atividades acessórias (gestão, TI, limpeza hospitalar) podem não se enquadrar no benefício. Faça simulação comparativa antes e depois da reforma.',
      baseLegal: 'LC 214/2025, regime diferenciado para saúde.',
    },
    relatedArticles: ['credito-amplo', 'aliquota-referencia', 'lucro-presumido'],
    planActionIds: ['top30_items', 'pricing_formula'],
  },
  {
    id: 'educacao',
    title: 'Educação — benefícios fiscais e condições',
    summary: 'O setor educacional tem alíquota reduzida prevista, mas o benefício depende do tipo de serviço. Cursos livres e treinamentos corporativos podem ter enquadramento diferente.',
    category: 'setores',
    categoryLabel: 'Setores da Economia',
    tags: ['educacao', 'escola', 'curso', 'ensino', 'aliquota-reduzida', 'treinamento'],
    icon: 'GraduationCap',
    difficulty: 'intermediario',
    readTime: 3,
    lawBasis: ['LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'A LC 214/2025 prevê alíquota reduzida para serviços de educação básica, fundamental, médio e superior. Cursos livres, treinamentos corporativos e e-learning podem ter enquadramento diferente dependendo da regulamentação.',
      oquemudata: 'Uma escola de ensino fundamental que hoje paga ISS de 2-3% pode ter carga alterada com o novo sistema dependendo do enquadramento. Instituições com fins lucrativos podem ter tratamento diferente de entidades sem fins lucrativos.',
      oquefarzer: 'Verifique o enquadramento de cada modalidade de ensino prestada. Se oferece cursos presenciais, online e treinamentos corporativos, cada um pode ter tratamento diferente. Consulte assessoria tributária para mapear o impacto por tipo de serviço.',
      baseLegal: 'LC 214/2025, regime diferenciado para educação.',
    },
    relatedArticles: ['credito-amplo', 'aliquota-referencia', 'lucro-presumido'],
    planActionIds: ['top30_items'],
  },
  {
    id: 'industria',
    title: 'Indústria — créditos na cadeia produtiva',
    summary: 'A indústria é um dos setores que mais se beneficia do crédito amplo: praticamente todos os insumos, matérias-primas e serviços usados na produção geram crédito.',
    category: 'setores',
    categoryLabel: 'Setores da Economia',
    tags: ['industria', 'producao', 'insumos', 'credito', 'ipi', 'cadeia-produtiva'],
    icon: 'Factory',
    difficulty: 'intermediario',
    readTime: 4,
    lawBasis: ['EC 132/2023', 'LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'Para a indústria, IBS e CBS substituem IPI, ICMS, PIS e COFINS nas operações de produção e venda. O crédito amplo permite que todos os insumos, matérias-primas, embalagens, energia elétrica e serviços usados na produção gerem crédito integralmente.',
      oquemudata: 'Uma indústria que hoje tem crédito restrito de IPI e PIS/COFINS passará a creditar praticamente tudo que compra. O IPI será gradualmente substituído pelo IS apenas para produtos prejudiciais à saúde e ao ambiente — os demais produtos industriais perdem o IPI sem substituto direto, o que pode representar redução de carga.',
      oquefarzer: 'Faça mapeamento completo dos insumos atuais e calcule o crédito que cada um gerará com o CBS. Simule a carga tributária efetiva (IBS+CBS menos créditos) comparada à atual (IPI+ICMS+PIS+COFINS menos créditos). O resultado pode ser surpreendentemente favorável.',
      baseLegal: 'EC 132/2023; LC 214/2025; disposições sobre extinção do IPI.',
    },
    relatedArticles: ['credito-amplo', 'imposto-seletivo', 'regime-monofasico'],
    planActionIds: ['top30_items', 'catalog_std', 'supplier_abc'],
  },
  {
    id: 'servicos-financeiros',
    title: 'Serviços Financeiros — exclusão e operações mistas',
    summary: 'Serviços financeiros estão excluídos do IBS e CBS. Mas empresas com atividades mistas precisam separar cada operação com precisão para evitar autuação.',
    category: 'setores',
    categoryLabel: 'Setores da Economia',
    tags: ['financeiro', 'banco', 'seguro', 'corretora', 'exclusao', 'operacoes-mistas'],
    icon: 'Landmark',
    difficulty: 'avancado',
    readTime: 4,
    lawBasis: ['LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'A LC 214/2025 exclui os serviços financeiros do escopo do IBS e CBS. Bancos, seguradoras, corretoras e instituições financeiras reguladas continuam sob tributação específica (IOF, PIS/COFINS com alíquotas próprias).',
      oquemudata: 'Para empresas puramente financeiras, a reforma tem impacto menor. O problema surge para empresas com atividades mistas: uma empresa que vende produtos e oferece financiamento ao consumidor precisa separar as operações. A parte de venda seguirá o regime IBS/CBS; a parte financeira, o regime específico. A separação incorreta gera autuação.',
      oquefarzer: 'Se sua empresa tem qualquer atividade financeira (financiamento próprio, consórcio, seguros), identifique e segregue contabilmente essas receitas das demais operações. Cada uma seguirá um regime tributário diferente.',
      baseLegal: 'LC 214/2025, exclusões do âmbito de incidência.',
    },
    relatedArticles: ['ibs', 'cbs', 'lucro-real'],
    planActionIds: ['governance_setup', 'fiscal_routine'],
  },
  {
    id: 'simples-nacional',
    title: 'Simples Nacional — permanecer ou optar pelo regime regular?',
    summary: 'A reforma transforma a opção pelo Simples em decisão estratégica para quem vende para empresas. A permanência no Simples pode reduzir sua competitividade B2B.',
    category: 'regimes',
    categoryLabel: 'Regimes Tributários',
    tags: ['simples-nacional', 'das', 'b2b', 'credito', 'competitividade', 'micro', 'pequena'],
    icon: 'Users',
    difficulty: 'intermediario',
    readTime: 5,
    lawBasis: ['LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'A LC 214/2025 permite que optantes do Simples Nacional escolham recolher IBS e CBS pelo regime regular (fora do DAS), gerando crédito pleno para seus clientes. Essa opção é voluntária.',
      oquemudata: 'Uma empresa do Simples que vende para outras empresas (B2B) enfrenta um dilema: se permanecer no Simples sem optar pelo regime regular, seus clientes só aproveitarão crédito proporcional ao recolhido no DAS — geralmente muito menor que a alíquota cheia. Isso torna seus preços menos atrativos para compradores que apuram créditos. A permanência no Simples deixou de ser automática.',
      oquefarzer: 'Se você vende principalmente para outras empresas, simule o impacto de permanecer no Simples vs. optar pelo regime regular. Consulte seu contador ou advogado tributarista — essa é uma das decisões mais urgentes de 2026.',
      baseLegal: 'LC 214/2025, Arts. sobre Simples Nacional e opção pelo regime regular de IBS/CBS.',
    },
    relatedArticles: ['credito-amplo', 'calendario-transicao', 'mei-microempresa'],
    planActionIds: ['simples_option'],
  },
  {
    id: 'lucro-presumido',
    title: 'Lucro Presumido na Reforma',
    summary: 'Empresas no Lucro Presumido precisam simular se o regime continua vantajoso: a CBS substitui PIS/COFINS com crédito amplo, o que pode representar aumento de carga para quem tem poucos insumos.',
    category: 'regimes',
    categoryLabel: 'Regimes Tributários',
    tags: ['lucro-presumido', 'pis', 'cofins', 'cbs', 'regime', 'simulacao'],
    icon: 'PieChart',
    difficulty: 'intermediario',
    readTime: 4,
    lawBasis: ['LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'No Lucro Presumido, PIS e COFINS hoje são cumulativos (0,65% + 3% = 3,65% sobre a receita) sem crédito. Com a CBS, o regime passa a ser não-cumulativo com crédito amplo — o que muda radicalmente a lógica de apuração.',
      oquemudata: 'Uma empresa de serviços no Lucro Presumido que paga 3,65% de PIS/COFINS hoje (sem crédito) pode passar a pagar uma alíquota maior de CBS — mas com crédito de todos os serviços e insumos contratados. O resultado líquido depende do quanto a empresa gasta em insumos que gerarão crédito. Para empresas com poucos insumos, a CBS pode representar aumento de carga.',
      oquefarzer: 'Calcule a diferença entre PIS/COFINS atual e CBS projetada, deduzindo os créditos que serão gerados. Verifique com seu contador se o Lucro Presumido ainda é o regime mais vantajoso a partir de 2027.',
      baseLegal: 'LC 214/2025; RIR/2018 (Lucro Presumido).',
    },
    relatedArticles: ['cbs', 'credito-amplo', 'lucro-real', 'split-payment'],
    planActionIds: ['regime_transition', 'fiscal_routine'],
  },
  {
    id: 'lucro-real',
    title: 'Lucro Real na Reforma',
    summary: 'Para empresas no Lucro Real, a reforma traz a maior oportunidade de crédito já vista no sistema brasileiro — mas exige controles mais rigorosos.',
    category: 'regimes',
    categoryLabel: 'Regimes Tributários',
    tags: ['lucro-real', 'cbs', 'credito', 'controle', 'grande-empresa', 'nao-cumulativo'],
    icon: 'Shield',
    difficulty: 'avancado',
    readTime: 4,
    lawBasis: ['LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'Empresas no Lucro Real que recolhem PIS/COFINS não-cumulativos já têm direito a crédito em algumas situações. Com a CBS, o crédito se torna amplo: quase todas as despesas geram crédito. O IBS também segue a não-cumulatividade plena.',
      oquemudata: 'Uma grande empresa do Lucro Real passará a creditar praticamente tudo: aluguéis, TI, consultoria, energia, limpeza, viagens. Isso pode representar redução significativa da carga tributária efetiva. A contrapartida é maior complexidade nos controles para rastrear e documentar todos os créditos.',
      oquefarzer: 'Revise o sistema de controle de créditos tributários. Garanta que todas as notas fiscais de entrada estarão corretamente cadastradas. A qualidade do cadastro fiscal deixa de ser boa prática e vira obrigação financeira.',
      baseLegal: 'LC 214/2025; RIR/2018 (Lucro Real).',
    },
    relatedArticles: ['cbs', 'credito-amplo', 'lucro-presumido', 'infracoes-penalidades'],
    planActionIds: ['supplier_abc', 'supplier_nf_quality', 'fiscal_routine'],
  },
  {
    id: 'mei-microempresa',
    title: 'MEI e Microempresa — impactos práticos',
    summary: 'MEIs e microempresas continuam no Simples Nacional, mas quem vende para empresas (B2B) pode perder competitividade se não avaliar a opção pelo regime regular de IBS/CBS.',
    category: 'regimes',
    categoryLabel: 'Regimes Tributários',
    tags: ['mei', 'microempresa', 'simples-nacional', 'b2b', 'b2c', 'pequeno-negocio'],
    icon: 'CreditCard',
    difficulty: 'basico',
    readTime: 3,
    lawBasis: ['LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'MEIs e microempresas continuam no Simples Nacional com tratamento favorecido. A reforma não elimina o Simples. Porém, a questão do crédito de IBS/CBS para clientes B2B afeta a competitividade no mercado corporativo.',
      oquemudata: 'Um MEI que presta serviços para empresas pode ver seus clientes preferirem fornecedores que oferecem crédito pleno de IBS/CBS. Isso pode pressionar MEIs a avaliarem a opção pelo regime regular — o que aumenta complexidade operacional mas mantém competitividade.',
      oquefarzer: 'Mapeie quem são seus principais clientes (PF ou PJ). Se vende principalmente para pessoas físicas (B2C), o impacto é menor. Se vende para empresas (B2B), avalie a opção pelo regime regular com seu contador.',
      baseLegal: 'LC 214/2025; LC 123/2006 (Simples Nacional) conforme alterada.',
    },
    relatedArticles: ['simples-nacional', 'credito-amplo', 'calendario-transicao'],
    planActionIds: ['simples_option', 'governance_setup'],
  },
  {
    id: 'contratos-longo-prazo',
    title: 'Contratos de Longo Prazo — como se proteger',
    summary: 'Contratos firmados antes da reforma que se estendem até 2027 ou além precisam de cláusula de revisão tributária. Sem ela, o prestador absorve sozinho o aumento de carga.',
    category: 'contratos',
    categoryLabel: 'Contratos e Preços',
    tags: ['contratos', 'longo-prazo', 'revisao', 'clausula-tributaria', 'b2b', 'protecao'],
    icon: 'FileText',
    difficulty: 'intermediario',
    readTime: 5,
    lawBasis: ['LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'A LC 214/2025 não obriga automaticamente a revisão de contratos privados em vigor. Porém, o princípio da onerosidade excessiva (Art. 478, Código Civil) e o equilíbrio econômico-financeiro podem ser invocados quando a reforma gerar impacto significativo na carga tributária de contratos já assinados.',
      oquemudata: 'Uma empresa com contrato de prestação de serviços de 3 anos assinado em 2024, com ISS de 2% e PIS/COFINS de 3,65%, pode se ver recolhendo IBS+CBS muito maior a partir de 2027 — sem poder repassar ao cliente se o contrato não tem cláusula de revisão. Esse é um dos maiores riscos financeiros da reforma para empresas B2B.',
      oquefarzer: 'Revise todos os contratos de longo prazo vigentes. Identifique os que não têm cláusula de revisão por alteração de legislação tributária. Consulte advogado para incluir aditivo contratual prevendo o reequilíbrio — enquanto ainda é possível negociar amigavelmente.',
      baseLegal: 'Art. 478, Código Civil (onerosidade excessiva); LC 214/2025.',
    },
    relatedArticles: ['reajuste-precos', 'contratos-governo', 'calendario-transicao'],
    planActionIds: ['contracts_review'],
  },
  {
    id: 'reajuste-precos',
    title: 'Reajuste de Preços — quem paga a conta?',
    summary: 'A reforma muda a carga efetiva para muitas empresas. Quem absorve a diferença — vendedor ou comprador — depende do poder de barganha e da estrutura de cada mercado.',
    category: 'contratos',
    categoryLabel: 'Contratos e Preços',
    tags: ['precos', 'reajuste', 'margem', 'competitividade', 'precificacao', 'carga-tributaria'],
    icon: 'RefreshCw',
    difficulty: 'intermediario',
    readTime: 4,
    lawBasis: ['EC 132/2023', 'LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'A reforma não determina quem deve absorver variações de carga tributária em relações privadas. O princípio econômico é que IBS e CBS, como tributos sobre o consumo, devem ser repassados ao preço final. Na prática, o mercado decide.',
      oquemudata: 'Para empresas com alto poder de barganha sobre fornecedores, a pressão será para que o fornecedor absorva o aumento. Para empresas com baixo poder de barganha, o repasse ao consumidor pode ser limitado pela concorrência. Setores com margens apertadas são os mais vulneráveis.',
      oquefarzer: 'Calcule o impacto da reforma na sua margem antes de qualquer reajuste. Identifique quais produtos podem absorver o aumento e quais precisam de repasse. Prepare a comunicação de reajuste para clientes com antecedência e dados concretos.',
      baseLegal: 'EC 132/2023; LC 214/2025; princípios gerais do direito contratual.',
    },
    relatedArticles: ['contratos-longo-prazo', 'split-payment', 'varejo-comercio'],
    planActionIds: ['pricing_formula', 'b2c_pricing_comms', 'margin_calc'],
  },
  {
    id: 'contratos-governo',
    title: 'Contratos com o Governo — reequilíbrio econômico-financeiro',
    summary: 'Fornecedores do governo têm direito ao reequilíbrio econômico-financeiro do contrato quando a reforma tributária alterar sua carga. Esse direito precisa ser exercido formalmente.',
    category: 'contratos',
    categoryLabel: 'Contratos e Preços',
    tags: ['governo', 'licitacao', 'contrato-publico', 'reequilibrio', 'lei-licitacoes'],
    icon: 'Landmark',
    difficulty: 'avancado',
    readTime: 4,
    lawBasis: ['LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'A Lei 14.133/2021 (Nova Lei de Licitações) garante o reequilíbrio econômico-financeiro dos contratos públicos quando há alteração de legislação tributária que impacte os custos do contratado. Esse direito é constitucional.',
      oquemudata: 'Uma empresa com contrato de fornecimento para o governo que tem sua carga tributária alterada com o IBS+CBS tem direito de solicitar revisão dos valores do contrato. O processo exige documentação técnica e proposta formal — não é automático.',
      oquefarzer: 'Mapeie todos os contratos públicos vigentes. Calcule o impacto da reforma na carga tributária de cada um. Contrate assessoria jurídica para preparar o pedido formal de reequilíbrio no momento adequado.',
      baseLegal: 'Art. 124, Lei 14.133/2021 (Nova Lei de Licitações); LC 214/2025.',
    },
    relatedArticles: ['contratos-longo-prazo', 'reajuste-precos', 'calendario-transicao'],
    planActionIds: ['gov_contracts', 'contracts_review'],
  },
  {
    id: 'operacoes-entre-estados',
    title: 'Operações entre Estados — tributação no destino',
    summary: 'O IBS é cobrado no estado do consumidor, não mais na origem. Isso elimina a guerra fiscal entre estados e simplifica radicalmente o compliance interestadual.',
    category: 'contratos',
    categoryLabel: 'Contratos e Preços',
    tags: ['interestadual', 'destino', 'guerra-fiscal', 'difal', 'multiestado', 'icms'],
    icon: 'Home',
    difficulty: 'intermediario',
    readTime: 4,
    lawBasis: ['EC 132/2023', 'LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'A EC 132/2023 estabelece que o IBS segue o princípio do destino: o tributo pertence ao estado e município onde está o consumidor final. Isso elimina a guerra fiscal entre estados, que hoje disputam empresas com benefícios de ICMS.',
      oquemudata: 'Hoje, quem vende para vários estados controla alíquotas interestaduais de ICMS diferentes, calcula DIFAL e lida com 27 legislações. Com o IBS, há uma alíquota nacional e a distribuição entre estados é feita automaticamente pelo Comitê Gestor. Para empresas multiestadais, isso simplifica enormemente o compliance.',
      oquefarzer: 'Revise a parametrização do ERP para operações interestaduais. O DIFAL será extinto gradualmente — verifique os prazos. Mapeie os benefícios fiscais de ICMS estaduais que sua empresa aproveita: serão extintos com a transição.',
      baseLegal: 'EC 132/2023, princípio do destino; LC 214/2025, Comitê Gestor do IBS.',
    },
    relatedArticles: ['ibs', 'aliquota-referencia', 'varejo-comercio'],
    planActionIds: ['multistate_erp'],
  },
  {
    id: 'infracoes-penalidades',
    title: 'Infrações e Penalidades — o que evitar',
    summary: 'A LC 227/2026 detalha 22 tipos de infrações com multas de 1 UPF (R$ 200) a 150% do tributo. Em 2026, autos por obrigações acessórias dão 60 dias para sanar sem penalidade. A partir de 2027, as multas são plenas.',
    category: 'planejamento',
    categoryLabel: 'Planejamento e Adequação',
    tags: ['infracoes', 'penalidades', 'multas', 'compliance', 'obrigacoes', 'autuacao'],
    icon: 'AlertTriangle',
    difficulty: 'intermediario',
    readTime: 6,
    lawBasis: ['LC 214/2025', 'LC 227/2026'],
    featured: false,
    sections: {
      oquedizalei: 'A LC 227/2026 (Arts. 341-A a 341-H) institui a Unidade Padrão Fiscal (UPF = R$ 200,00, corrigida anualmente pelo IPCA) como base de cálculo das multas acessórias. Para tributo não pago: multa de 75% em lançamento de ofício; 50% se a declaração estava correta mas o pagamento não foi feito; 100% em caso de sonegação ou fraude; 150% em reincidência (nova infração qualificada dentro de 3 anos). Multas acessórias variam de 1 UPF por documento omitido até 150 UPF por equipamento com software fraudulento, e de 33% a 100% do valor do tributo de referência para infrações em documentos fiscais. Penalidades são cumulativas quando há descumprimento simultâneo de obrigação principal e acessória. Redução possível: 50% se pago integralmente antes da impugnação; 40% se parcelado no mesmo prazo; 30% se pago após impugnação mas antes da inscrição em dívida ativa; 20% se parcelado nessa fase.',
      oquemudata: 'Em 2026 (ano de teste), o tributo de referência para cálculo das penalidades é: CBS = 6% do valor da operação; IBS = 12% do valor da operação (Art. 341-G §5 III). Importante: se lavrado auto de infração por descumprimento de obrigação acessória em 2026, a empresa tem 60 dias para sanar a omissão — sanada, a penalidade é extinta (Art. 348 §§3-4). A partir de 2027, as penalidades são calculadas sobre as alíquotas reais da CBS, sem essa válvula de escape. Reincidência específica em obrigações acessórias (mesma infração dentro de 3 anos) majora a multa em 50%.',
      oquefarzer: 'Use 2026 como janela de adequação: corrija agora os erros de emissão de NF, cadastro de produtos e escrituração antes que as multas plenas entrem em vigor em 2027. Estabeleça rotina mensal de conferência de notas de entrada e saída. Documente todos os créditos aproveitados com nota fiscal regular do fornecedor — crédito indevido gera multa de 75% do valor. Se receber auto de infração por obrigação acessória em 2026, aja imediatamente: os 60 dias para sanar extinguem a penalidade. Em caso de autuação, avalie o pagamento imediato para obter redução de 50% da multa.',
      baseLegal: 'LC 227/2026, Arts. 341-A (conceito de infração), 341-C (UPF = R$ 200), 341-D (cumulatividade), 341-F (multas punitivas: 75%/100%/150%), 341-G (multas acessórias: 22 tipos), 341-H (reduções: 50%/40%/30%/20%), Art. 348 §§3-4 (prazo de 60 dias em 2026).',
    },
    relatedArticles: ['nota-fiscal', 'ano-informativo-2026', 'credito-amplo'],
    planActionIds: ['fiscal_routine', 'nf_formal', 'governance_setup'],
  },
  {
    id: 'planejamento-tributario',
    title: 'Planejamento Tributário Lícito na Transição',
    summary: 'O período de transição 2026–2033 abre oportunidades legítimas: escolha de regime, timing de operações, revisão de contratos e estrutura societária.',
    category: 'planejamento',
    categoryLabel: 'Planejamento e Adequação',
    tags: ['planejamento-tributario', 'elisao', 'regime', 'estrutura-societaria', 'otimizacao'],
    icon: 'CheckSquare',
    difficulty: 'avancado',
    readTime: 5,
    lawBasis: ['EC 132/2023', 'LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'O planejamento tributário lícito (elisão fiscal) é protegido pelo ordenamento jurídico brasileiro. A LC 214/2025 não elimina essa possibilidade — ao contrário, a complexidade da transição cria novas oportunidades legítimas de otimização.',
      oquemudata: 'As principais oportunidades de planejamento na transição incluem: (1) escolha do regime considerando a nova lógica de crédito; (2) timing de operações — antecipar ou diferir receitas considerando percentuais diferentes de IBS/CBS por ano; (3) revisão da estrutura societária para separar atividades com regimes distintos; (4) opção pelo regime regular no Simples Nacional; (5) revisão de contratos com cláusulas tributárias.',
      oquefarzer: 'Contrate revisão tributária completa com advogado ou contador especializado na reforma. O custo de uma consultoria preventiva é muito menor do que pagar tributo a maior ou sofrer autuação.',
      baseLegal: 'EC 132/2023; LC 214/2025; princípios constitucionais de legalidade e liberdade de planejamento.',
    },
    relatedArticles: ['calendario-transicao', 'simples-nacional', 'contratos-longo-prazo'],
    planActionIds: ['regime_transition', 'contracts_review', 'final_validation'],
  },
  {
    id: 'creditos-acumulados',
    title: 'Créditos Acumulados de ICMS, PIS e COFINS',
    summary: 'Créditos acumulados até o fim da transição têm regras específicas. Não identificá-los e utilizá-los dentro dos prazos pode significar perda de valores relevantes.',
    category: 'planejamento',
    categoryLabel: 'Planejamento e Adequação',
    tags: ['creditos-acumulados', 'icms', 'pis', 'cofins', 'ressarcimento', 'compensacao', 'exportacao'],
    icon: 'TrendingUp',
    difficulty: 'avancado',
    readTime: 5,
    lawBasis: ['EC 132/2023', 'LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'A EC 132/2023 e a LC 214/2025 estabelecem regras de transição para créditos acumulados de ICMS, PIS e COFINS. Créditos reconhecidos judicialmente e saldos credores têm formas específicas de compensação ou ressarcimento durante a transição.',
      oquemudata: 'Empresas exportadoras ou que acumulam crédito de ICMS por operações com saídas isentas podem ter direito a ressarcimento ou compensação antes que o ICMS seja extinto em 2033. Créditos de PIS/COFINS acumulados no Lucro Real também precisam ser identificados e aproveitados dentro dos prazos. Perder esses créditos pode representar prejuízo financeiro significativo.',
      oquefarzer: 'Faça levantamento completo dos créditos de ICMS, PIS e COFINS em aberto. Identifique créditos que podem ser transferidos, compensados ou ressarcidos durante a transição. Contrate análise especializada se o volume for relevante.',
      baseLegal: 'EC 132/2023, disposições transitórias; LC 214/2025, capítulo sobre transição de créditos de tributos extintos.',
    },
    relatedArticles: ['credito-amplo', 'calendario-transicao', 'planejamento-tributario'],
    planActionIds: ['final_validation'],
  },
  {
    id: 'cashback',
    title: 'Cashback do IBS/CBS — devolução para baixa renda',
    summary: 'A reforma prevê devolução de parte do IBS e CBS para famílias de baixa renda via CadÚnico — mecanismo de progressividade fiscal inédito no Brasil.',
    category: 'fundamentos',
    categoryLabel: 'Fundamentos',
    tags: ['cashback', 'baixa-renda', 'cadunico', 'progressividade', 'consumidor-final'],
    icon: 'Heart',
    difficulty: 'basico',
    readTime: 2,
    lawBasis: ['EC 132/2023', 'LC 214/2025'],
    featured: false,
    sections: {
      oquedizalei: 'O Art. 6º, §3º da EC 132/2023 prevê devolução de IBS e CBS para pessoas físicas de baixa renda como compensação pela regressividade dos impostos sobre consumo. A LC 214/2025 regulamenta esse cashback via CadÚnico.',
      oquemudata: 'Para as empresas, o cashback não gera obrigação direta. Mas é relevante para o varejo popular: a devolução do tributo ao consumidor de baixa renda aumenta seu poder de compra. É também um argumento de comunicação — o novo sistema inclui mecanismo de justiça fiscal inédito no Brasil.',
      oquefarzer: 'Acompanhe a regulamentação do cashback. Se sua empresa vende ao consumidor final de baixa renda, entender como o cashback funciona pode ser um diferencial de comunicação comercial.',
      baseLegal: 'Art. 6º, §3º, EC 132/2023; LC 214/2025, regulamentação do cashback.',
    },
    relatedArticles: ['varejo-comercio', 'aliquota-referencia', 'calendario-transicao'],
    planActionIds: ['b2c_pricing_comms'],
  },
];
